# Generated by Django 5.0.6 on 2024-07-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_review_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
