# Generated by Django 5.0.6 on 2024-08-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='online_status',
            field=models.BooleanField(default=True),
        ),
    ]
