# Generated by Django 5.0.6 on 2024-08-08 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_schedule_online_status'),
        ('order', '0006_orders_captain_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='route_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_route_end', to='order.location', verbose_name='Route End'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='route_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_route_start', to='order.location', verbose_name='Route Start'),
        ),
    ]
